### ISSUE TITLE
http://localhost:8000/lamp doesn't work

### ISSUE THREAD

**Issue by Appstun** [VedalAI/neurosama.com#2]
This doesn't get me the color of Neuro's lava lamp.
please fix

**Comment by AngeloTadeucci** [comment]
Make your own server

**Comment by KornineQ** [comment]
You need server

**Comment by xDarkEXE** [comment]
you will need a server for it to function correctly, and make sure it is running on port 8000

**Comment by Appstun** [comment]
oh ... and how do i get the color?

**Comment by fr0lnx** [comment]
make a script that grabs it from the stream

**Comment by Appstun** [comment]
so i need a server on port 8000 and the server grabs the current image from the stream and looks in the right bottom corner to get the color?

**Comment by xDarkEXE** [comment]
i would say, that is what you will have to create.

**Comment by Appstun** [comment]
ok ... thanks you all ❤️
